dependencies:
  - python-requests
  - python-beautifulsoup
  - python-requests
  - python-gevent
  - python-decorator
  - python-libtorrent
  - python-pyside
  - subliminal
releases:
  - saucy
  - precise
  - quantal
  - raring
