section: net
dependencies:
  - python-requests
  - python-beautifulsoup
  - python-gevent
  - python-decorator
  - python-libtorrent
  - python-pyside
  - subliminal
releases:
  - trusty
  - saucy
  - precise
  - quantal
