language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount python-pyside
  - pip install coverage
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cat setup.py|grep -v pyside > new_setup.py
  - mv new_setup.py setup.py
install:
  - pip install -U .
script:
  - nosetests --with-coverage 2>test_out
after_script:
  - coverage report
  - covio
